version: "3"
services:
  recv_hls_service:
    build:
      context: ./../../../../
      dockerfile: examples/echo_service/_service/Dockerfile
    networks:
      - local-network
  recv_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/modes/classic/recv_hls
    networks:
      - local-network
      - hidden-lake
  send_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/echo_service/modes/classic/send_hls
    ports:
      - 7572:7572
    networks:
      - hidden-lake
networks:
  local-network:
    driver: bridge
  hidden-lake:
    driver: bridge
