version: "3"
services:
  recv_hls_service:
    build:
      context: ./../../../
      dockerfile: examples/echo_service/_service/Dockerfile
    networks:
      - local-network
  recv_hls:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=some_test_network
      - SERVICE_PATH=examples/echo_service/networks/recv_hls
    networks:
      - local-network
      - hidden-lake
  send_hls:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=some_test_network
      - SERVICE_PATH=examples/echo_service/networks/send_hls
    ports:
      - 7572:7572
    networks:
      - hidden-lake
  middle_hla_tcp:
    build:
      context: ./../../../
      dockerfile: cmd/hla/hla_tcp/Dockerfile
    environment:
      - SERVICE_NETWORK=some_test_network
      - SERVICE_PATH=examples/echo_service/networks/middle_hla_tcp
    networks:
      - hidden-lake
networks:
  local-network:
    driver: bridge
  hidden-lake:
    driver: bridge
